version: "3.8"

services:
  traefik:
    image: traefik:v2.4
    command: --api.insecure=true
      --providers.docker
      --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - todanni

  postgresql:
    image: postgres
    container_name: postgres-db
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - todanni
    ports:
      - "127.0.0.1:5432:5432"

  vault: 
    image: vault
    container_name: vault
    volumes:
      - ./file:/vault/file:rw
      - ./config:/vault/config:rw
    cap_add:
      - IPC_LOCK
    networks:
      - todanni
    command: vault server -config=/vault/config/vault.json
    

volumes:
  postgres-data:

networks:
  todanni:
    name: todanni
