version: "3.8"

services:
  traefik:
    image: traefik:v2.4
    command: --api.insecure=true
      --providers.docker
      --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - todanni
    labels:
      com.datadoghq.ad.logs: 'traefik'

  postgresql:
    image: postgres
    container_name: postgres-db
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - todanni
    ports:
      - "127.0.0.1:5432:5432"
    labels:
      com.datadoghq.ad.logs: 'postgres'

  vault: 
    image: vault
    container_name: vault
    volumes:
      - ./file:/vault/file:rw
      - ./config:/vault/config:rw
    cap_add:
      - IPC_LOCK
    networks:
      - todanni
    ports: 
      - "8200:8200"
    command: vault server -config=/vault/config/vault.json
    labels:
      com.datadoghq.ad.logs: 'vault'


  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=docker
      - RABBITMQ_DEFAULT_PASS=docker
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - todanni

  datadog:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=b8f2c7f1e26f56304ff6cd8e6a57daf9
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE_LOGS="name:datadog-agent"
      - DD_SITE="datadoghq.eu"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro


volumes:
  postgres-data:

networks:
  todanni:
    name: todanni
