http:
  routers:
   vault:
    entrypoints:
      - "https"
    rule: "Host(`vault.todanni.com`)"
    tls:
     certresolver: letsencrypt
    service: vault
  
  services:
    vault:
      loadBalancer:
        servers:
          - url: "http://10.106.0.2:8200"