name: Development - re-deploy

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: copy repo contents via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_HOSTNAME}}
          username: root
          key: ${{ secrets.ADMIN_SSH_KEY }}
          source: "*"
          target: "/root/todanni/orchestrate"
          overwrite: true
      -
        name: Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_DO_DROPLET_IP }}
          username: root
          key: ${{ secrets.ADMIN_SSH_KEY }}
          script: |
            cd /root/todanni/orchestrate/
            docker-compose --file dev-docker-compose.yml down
            docker-compose --file dev-docker-compose.yml up -d
      -
        name: Send discord failure message
        if: ${{ failure() }}
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#FF0000"
          message: "Failed to run Dev images for ${{ github.repository }} \n https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}}"

      -
        name: Send discord success message
        if: ${{ success() }}
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#48f442"
          message: "Dev is now running latest images for ${{ github.repository }}. \n https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}}"

